apiVersion: apps/v1
kind: Deployment
metadata:
  name: usersapi
  namespace: user
  labels:
    app: user-api
spec:
  selector:
    matchLabels:
      app: user-api
  template:
    metadata:
      labels:
        app: user-api
    spec:
      containers:
      - name: userapi
        image: kasinenichandu/users-api
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 1025
