apiVersion: apps/v1
kind: Deployment
metadata:
  name: userui
  namespace: admin
  labels:
    app: ad-ui
spec:
  selector:
    matchLabels:
      app: ad-ui
  template:
    metadata:
      labels:
        app: ad-ui
    spec:
      containers:
      - name: usersui
        image: kasinenichandu/admin-ui
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
        ports:
        - containerPort: 3000
