apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminapi
  namespace: admin
  labels:
    app: add-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: add-api
  template:
    metadata:
      labels:
        app: add-api
    spec:
      containers:
      - name: adminapi
        image: kasinenichandu/admin-api
        resources:
          requests:
            cpu: "250m"
            memory: "1Gi"
          limits:
            cpu: "500m"
            memory: "2Gi"
          env:

        ports:
        - containerPort: 1025

      
